import type { Metadata } from "next";
import "@/css/global.css";
import { grotesk, oswald } from "@/fonts/main";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${oswald.variable} ${grotesk.variable} antialiased bg-secondary`}
      >
        {children}
      </body>
    </html>
  );
}
