import type { Metadata } from "next";
import "@/css/global.css";
import { clashDisplay, clashGrotesk, geist, jakarta, satoshi } from "@/fonts/main";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl-PL">
      <body
        className={`${clashDisplay.variable} ${clashGrotesk.variable} ${jakarta.variable} ${satoshi.variable} ${geist.variable} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
