import type { Metadata } from "next";
import "@/css/global.css";
import { clashDisplay, clashGrotesk, geist, jakarta, satoshi } from "@/fonts/main";
import { Navigation } from "@/components/layout/navigation";
import NavigationProvider from "@/provider/NavigationProvider";
import { Footer } from "@/layout/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl-PL">
      <body
        className={`${clashDisplay.variable} ${clashGrotesk.variable} ${jakarta.variable} ${satoshi.variable} ${geist.variable} antialiased `}
      >
        <NavigationProvider>
          <Navigation/>
          {children}
          <Footer/>
        </NavigationProvider>
      </body>
    </html>
  );
}
